services:
  mongodb:
    container_name: vpo_mongo_prod
    image: mongo:5.0

  api:
    container_name: vpo_api_prod
    image: vpo_api_prod
    depends_on:
      - 'mongodb'
    build:
      context: .
      dockerfile: ./Dockerfile
      target: api_prod
    env_file:
      - ./apps/api/.env
    ports:
      - '3332:3332'
